# Site settings
title: Mike Tyka 
email: mike.tyka@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  Science Sculpture Artist, Biochemist, Googler, Glassblower, Creator of @groovikscube & @TheALTSpace
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mtyka.github.io/" # the base hostname & protocol for your site
twitter_username: mtyka 
github_username:  mtyka

# Build settings
markdown: kramdown
