# Site settings
title: Mike Tyka, PhD 
email: mike.tyka@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  Climate Research, AI & Media Art, Sculpture, Machine Learning, SciArt, Biochemistry, Glass Casting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mtyka.github.io/" # the base hostname & protocol for your site
twitter_username: mtyka 
github_username:  mtyka
#host: 0.0.0.0
# Build settings
markdown: kramdown

# BibTex Citation plugin
citation:
    citation_style: apa
    citation_locale: en
